### ISSUE TITLE
can you send yahoo letor datasets to my email? 

### ISSUE THREAD

**Issue by shenhuiyang** [QingyaoAi/Deep-Listwise-Context-Model-for-Ranking-Refinement#6]
The website can't download the datasets.

my email：854352859@qq.com
thank you!

**Comment by QingyaoAi** [comment]
You need to "purchase" (it's free) the dataset on the website (https://webscope.sandbox.yahoo.com/catalog.php?datatype=c, C14B - Yahoo! Learn to Rank Challenge version 2.0 (616 MB)) so that you could sign the necessary agreement documents to use the data. It usually just takes 1 or 2 days before they give you the downloadable link.
